# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

appname: "LogReader"
behind_proxy: 1
layout: "main"
charset: "UTF-8"
session: "YAML"
# session_dir: /tmp
template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
#         
logger: 'File'
engines:
   logger:
      File:
         log_dir: "/home/alfred/webapps/LogReader/logs"
         file_name: "deployment.log"
#
plugins:
 Database:
  connections:
   sqlserver:
    dsn: 'dbi:SQLite:dbname=/home/alfred/webapps/LogReader/logs/LogReader.db'
    username: ''
    password: ''
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
      PrintError: 1
